services:
  kroki:
    image: yuzutech/kroki:${KROKI_VERSION:-0.30.1}
    depends_on:
      - mermaid
    environment:
      KROKI_MERMAID_HOST: mermaid
    ports:
      - "127.0.0.1:${KROKI_PORT:-8990}:8000"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

  mermaid:
    image: yuzutech/kroki-mermaid:${KROKI_VERSION:-0.30.1}
    expose:
      - "8002"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
